DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

api/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from rest_framework.schemas import get_schema_view
from rest_framework_swagger.renderers import SwaggerUIRenderer, OpenAPIRenderer
from api.viewset import ViewSet
from django.contrib import admin


router = routers.DefaultRouter()
router.register(r'users', ViewSet.UserViewSet)

# Create our schema's view w/ the get_schema_view() helper method. Pass in the proper Renderers for swagger
schema_view = get_schema_view(title='Users API', renderer_classes=[OpenAPIRenderer, SwaggerUIRenderer])

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
	url(r'^docs/', schema_view, name="docs"),
	url(r'^api/', include(router.urls)),
	url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
	url(r'^admin/', admin.site.urls),
]

myproject/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.contrib.auth.models import User
from rest_framework import serializers, viewsets, routers
from DjangoUeditor import urls as djud_urls
from . import testdb, view, search, logon, addarctic
from blog import views
from django.conf import settings


# Serializers define the API representation.
class UserSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = User
        fields = ('url', 'username', 'email', 'is_staff')


# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


# Routers provide a way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
urlpatterns = [
    #url(r'^$', view.hello),
    #url(r'^', include(router.urls)),
    url(r'^admin/', admin.site.urls),
    url(r'^testdb$', testdb.testdb),
    url(r'^adddate$', testdb.adddata),
    url(r'^search-form$', search.search_form),
    url(r'^search$', search.search),
    url(r'^post$', search.search_post),
    url(r'^logon$', logon.logon),
    url(r'^signin$', logon.signin),
    url(r'^hello$', views.blog_index),
    url(r'^ueditor/', include(djud_urls)),
    url(r'^add$', addarctic.add),
    url(r'^indexfor$', views.blog_hello),
    url(r'^eveblog/$', views.eveblog),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^', include('rest_framework_swagger.urls')),
]
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

tutorial/tutorial/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('snippets.urls')),
    url(r'^api-auth/', include('rest_framework.urls')),
]

blog/models.py
# -*- coding: UTF-8 -*-
#from __future__ import unicode_literals
from django.db import models
from DjangoUeditor.models import UEditorField

class Article(models.Model):
    title = models.CharField(u'标题', max_length=256)
    category = models.CharField(u"博客标签", max_length=50, blank=True)  # 博客标签
    jianshu = models.TextField(u"概要")
    picture = models.TextField(u"图片地址")
    content = UEditorField(u"文章正文", height=300, width=1000, default=u'', blank=True, imagePath="uploads/blog/images/",
                           toolbars='besttome', filePath='uploads/blog/files/')

    pub_date = models.DateTimeField(u'发表时间', auto_now_add=True, editable=True)
    update_time = models.DateTimeField(u'更新时间', auto_now=True, null=True)

    def __unicode__(self):
        return self.title
class User(models.Model):
    name = models.CharField(u'name', max_length=256)
    password = models.TextField(u'password')

    def __unicode__(self):
        return self.name

templates/add.html
<!DOCTYPE html>

<html lang="zh-hans" >
<head>
<title>添加文章</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css" />
<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css" />


<script type="text/javascript" src="/admin/jsi18n/"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>
<script type="text/javascript" src="/static/ueditor/ueditor.config.js"></script>
<script type="text/javascript" src="/static/ueditor/ueditor.all.min.js"></script>

<meta name="robots" content="NONE,NOARCHIVE" />
</head>


<body class=" app-blog model-article change-form"
  data-admin-utc-offset="0">

<!-- Container -->
<div id="container">

    
    <!-- Header -->
    <div id="header">
        <div id="branding">
        
<h1 id="site-name"><a href="/admin/">文章管理</a></h1>
        </div>
    </div>
    <!-- END Header -->
<div class="breadcrumbs">
<a href="/hello">首页</a>
&rsaquo; <a href="/add">添加文章</a>
</div>
    <!-- Content -->
    <div id="content" class="colM">
        <div id="content-main">
<div>
<form action="/add" method="post">
    {% csrf_token %}
  <fieldset class="module aligned ">
        <div class="form-row field-title">
                <div>
                        <label class="required" for="id_title">标题:</label>
                            <input class="vTextField" id="id_title" maxlength="256" name="title" type="text" required />
                </div>
        </div>
        <div class="form-row field-category">
                <div>
                        <label for="id_category">博客标签:</label>
                            <input class="vTextField" id="id_category" maxlength="50" name="category" type="text" />
                </div>
        </div>
       <div class="form-row field-jianshu">
                <div>
                        <label class="required" for="id_jianshu">概要:</label>
                            <textarea class="vLargeTextField" cols="40" id="id_jianshu" name="jianshu" rows="10" required>
        </textarea>
                </div>
        </div>
        <div class="form-row field-content">
                <div>
                        <label for="id_content">文章正文:</label>
                             <script id="id_content" name="content"  style="display: inline-block;" type="text/plain">
 </script>
<script type="text/javascript">
    
    var id_content = UE.getEditor('id_content',{'toolbars': [['source', 'undo', 'redo', 'bold', 'italic', 'underline', 'forecolor', 'backcolor', 'superscript', 'subscript', 'justifyleft', 'justifycenter', 'justifyright', 'insertorderedlist', 'insertunorderedlist', 'blockquote', 'formatmatch', 'removeformat', 'autotypeset', 'inserttable', 'pasteplain', 'wordimage', 'searchreplace', 'map', 'preview', 'fullscreen'], ['insertcode', 'paragraph', 'fontfamily', 'fontsize', 'link', 'unlink', 'insertimage', 'insertvideo', 'attachment', 'emotion', 'date', 'time']], 'initialFrameWidth': 1000, 'initialFrameHeight': 300, 'serverUrl': '/ueditor/controller/?imagePathFormat=uploads%2Fblog%2Fimages%2F&filePathFormat=uploads%2Fblog%2Ffiles%2F'});
     id_content.ready(function(){
         
     });
</script>
                </div>
            
        </div>
    
</fieldset>
<form>
<div class="submit-row">
<input type="submit" value="保存" class="default" name="_save" />
<input type="submit" value="保存并增加另一个" name="_addanother" />
</div>
</form>
</div>

        </div>

        
        <br class="clear" />
    </div>
    <!-- END Content -->

    <div id="footer"></div>
</div>
<!-- END Container -->

</body>
</html>

templates/hello.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>JUST DO IT </title>
    <link rel="stylesheet" type="text/css" href="static/third/styles/shCore.css">
    <link rel="stylesheet" type="text/css" href="static/third/styles/shThemeDefault.css">
</head>
<body style="background-color:lightblue;">
    <form action="/hello" ><br>
{% for blog in blog_list %}
        <h2>{{ blog.title }}</h2>
    <p>{{ blog.pub_date }}</p>
        <p>{{blog.category}}</p>
        {% autoescape off %}
        <p>{{ blog.content }}</p>
        {% endautoescape %}
{% endfor %}
     </form>
    <a href="/add">写博客</a>
    </script>
    <script type="text/javascript" src="static/third/scripts/XRegExp.js"></script>
    <script type="text/javascript" src="static/third/scripts/shCore.js"></script>
    <script type="text/javascript" src="static/third/scripts/shBrushJava.js"></script>
    <script type="text/javascript" src="static/third/scripts/shBrushJScript.js"></script>
    <script type="text/javascript" src="static/third/scripts/shBrushSql.js"></script>
    <script type="text/javascript" src="static/third/scripts/shBrushPython.js"></script>
    <script type="text/javascript">
        SyntaxHighlighter.all()
    </script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Halcyon Days - An Exclusive Freebie for Codrops</title>
    <link href="static/css/bootstrap.min.css" rel="stylesheet">
    <link href="static/css/flexslider.css" rel="stylesheet" >
    <link href="static/css/styles.css" rel="stylesheet">
    <link href="static/css/queries.css" rel="stylesheet">
    <link href="static/css/animate.css" rel="stylesheet">
        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
      </head>
      <body id="top">
        <header id="home">
          <nav>
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-8 col-xs-offset-2">
                  <nav class="pull">
                    <ul class="top-nav">
                      <li><a href="#intro">Introduction <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                      <li><a href="#features">Features <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                      <li><a href="#responsive">Responsive Design <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                      <li><a href="#portfolio">Portfolio <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                      <li><a href="#team">Team <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                      <li><a href="#contact">Get in Touch <span class="indicator"><i class="fa fa-angle-right"></i></span></a></li>
                    </ul>
                  </nav>
                </div>
              </div>
            </div>
          </nav>
          <section class="hero" id="hero">
            <div class="container">
              <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center inner">
                  <h1 class="animated fadeInDown">NICE <span>DAYS</span></h1>
                  <p class="animated fadeInUp delay-05s">poem and live </p>
                </div>
              </div>
              <div class="row">
                <div class="col-md-6 col-md-offset-3 text-center">
                  <a href="/logon" class="learn-more-btn">log on</a>
                  <a href="/signin" class="learn-more-btn">sign up</a>
                </div>
              </div>
            </div>
          </section>
        </header>

      </body>
    </html>

templates/indexfor.html
<!doctype html>
<html lang="zh-hans">
<head>
<meta charset="utf-8">
<title>首页_WJ个人博客</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="static/css/base.css" rel="stylesheet">
<link href="static/css/index.css" rel="stylesheet">
<link href="static/css/m.css" rel="stylesheet">
<script src="static/js/js/jquery.min.js" type="text/javascript"></script>
<script src="static/js/js/jquery.easyfader.min.js"></script>
<script src="static/js/js/conn.js"></script>
<script src="static/js/js/nav.js"></script>
<script src="static/js/js/scrollReveal.js"></script>
<!--[if lt IE 9]>
<script src="static/js/js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header> 
  <!--menu begin-->
  <div class="menu">
    <nav class="nav" id="topnav">
      <h1 class="logo"><a href="http://www.yangqq.com">WJ博客</a></h1>
      <li><a href="/indexfor">网站首页</a> </li>
      <li><a href="static/html/about.html">关于我</a> </li>
      <li><a href="static/html/list.html">学无止境</a>
        <ul class="sub-nav">
          <li><a href="static/html/list.html">心得笔记</a></li>
        </ul>
      </li>
      <li><a href="static/html/life.html">慢生活</a>
        <ul class="sub-nav">
          <li><a href="static/html/life.html">日记</a></li>
          <li><a href="static/html/life.html">欣赏</a></li>
          <li><a href="static/html/life.html">程序人生</a></li>
          <li><a href="static/html/life.html">经典语录</a></li>
        </ul>
      </li>
      <li><a href="static/html/time.html">时间轴</a> </li>
      <li><a href="static/html/gbook.html">留言</a> </li>
      <li><a href="static/html/info.html">内容页</a> </li>
      <li><a href="/add">写博客</a> </li>
      <!--search begin-->
      <div id="search_bar" class="search_bar">
        <form  id="searchform" action="[!--news.url--]e/search/index.php" method="post" name="searchform">
          <input class="input" placeholder="想搜点什么呢..." type="text" name="keyboard" id="keyboard">
          <input type="hidden" name="show" value="title" />
          <input type="hidden" name="tempid" value="1" />
          <input type="hidden" name="tbname" value="news">
          <input type="hidden" name="Submit" value="搜索" />
          <span class="search_ico"></span>
        </form>
      </div>
      <!--search end--> 
    </nav>
  </div>
  <!--menu end--> 
  <!--mnav begin-->
  <div id="mnav">
    <h2><a href="http://www.yangqq.com" class="mlogo">WJ博客</a><span class="navicon"></span></h2>
    <dl class="list_dl">
      <dt class="list_dt"> <a href="index.html">网站首页</a> </dt>
      <dt class="list_dt"> <a href="about.html">关于我</a> </dt>
      <dt class="list_dt"> <a href="#">慢生活</a> </dt>
      <dd class="list_dd">
        <ul>
          <li><a href="life.html">日记</a></li>
          <li><a href="life.html">欣赏</a></li>
          <li><a href="life.html">程序人生</a></li>
          <li><a href="life.html">经典语录</a></li>
        </ul>
      </dd>
      <dt class="list_dt"> <a href="time.html">时间轴</a> </dt>
      <dt class="list_dt"> <a href="gbook.html">留言</a> </dt>
    </dl>
  </div>
  <!--mnav end--> 
</header>
<article> 
  <!--banner begin-->
 <div class="picsbox"> 
  <div class="banner">
    <div id="ban" class="fader">
      <li class="slide" ><a href="/" target="_blank"><img src="static/images/images/banner01.jpg"><span class="imginfo">LALALALALALALA</span></a></li>
      <li class="slide" ><a href="/" target="_blank"><img src="static/images/images/banner02.jpg"><span class="imginfo">LALALALALALALA</span></a></li>
      <li class="slide" ><a href="/" target="_blank"><img src="static/images/images/banner03.jpg"><span class="imginfo">LALALALALALALA</span></a></li>
      <div class="fader_controls">
        <div class="page prev" data-target="prev">&lsaquo;</div>
        <div class="page next" data-target="next">&rsaquo;</div>
        <ul class="pager_list">
        </ul>
      </div>
    </div>
  </div>
  <!--banner end-->
  <div class="toppic">
    <li> <a href="/" target="_blank"> <i><img src="static/images/images/toppic01.jpg"></i>
      <h2>别让这些闹心的套路，毁了你的网页设计!</h2>
      <span>学无止境</span> </a> </li>
    <li> <a href="/" target="_blank"> <i><img src="static/images/images/zd01.jpg"></i>
      <h2>个人博客，属于我的小世界！</h2>
      <span>学无止境</span> </a> </li>
  </div>
  </div>
  <div class="blank"></div>
  <!--blogsbox begin-->

  <div class="blogsbox">

      {% for blog in blog_list %}
      <div class="blogs" data-scroll-reveal="enter bottom over 1s" >
        <h3 class="blogtitle"><a href="/eveblog/?id={{ blog.id }}" target="_blank">{{ blog.title }}</a></h3>
          {% if blog.picture != '0' %}
          {% autoescape off %}
          <span class="blogpic"><a href="/" title="">{{ blog.picture }}</a></span>
           {% endautoescape %}
          {% endif %}
      <p class="blogtext">{{ blog.jianshu }}</p>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="/">WJ</a></li>
          <li class="lmname"><a href="/">{{ blog.category }}</a></li>
          <li class="timer">{{ blog.pub_date }}</li>
          <li class="view"><span>34567</span>已阅读</li>
          <li class="like">9999</li>
        </ul>
      </div>
    </div>
      {% endfor %}
  </div>
  <!--blogsbox end-->
  <div class="sidebar">
    <div class="zhuanti">
      <h2 class="hometitle">特别推荐</h2>
      <ul>
        <li> <i><img src="static/images/images/banner03.jpg"></i>
          <p>帝国cms调用方法 <span><a href="/">阅读</a></span> </p>
        </li>
        <li> <i><img src="static/images/images/b04.jpg"></i>
          <p>5.20 我想对你说 <span><a href="/">阅读</a></span></p>
        </li>
        <li> <i><img src="static/images/images/b05.jpg"></i>
          <p>个人博客，属于我的小世界！ <span><a href="/">阅读</a></span></p>
        </li>
      </ul>
    </div>
    <div class="tuijian">
      <h2 class="hometitle">推荐文章</h2>
      <ul class="tjpic">
        <i><img src="static/images/images/toppic01.jpg"></i>
        <p><a href="/">别让这些闹心的套路，毁了你的网页设计</a></p>
      </ul>
      <ul class="sidenews">
        <li> <i><img src="static/images/images/toppic01.jpg"></i>
          <p><a href="/">别让这些闹心的套路，毁了你的网页设计</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="static/images/images/toppic02.jpg"></i>
          <p><a href="/">给我模板PSD源文件，我给你设计HTML！</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="static/images/images/v1.jpg"></i>
          <p><a href="/">别让这些闹心的套路，毁了你的网页设计</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="static/images/images/v2.jpg"></i>
          <p><a href="/">给我模板PSD源文件，我给你设计HTML！</a></p>
          <span>2018-05-13</span> </li>
      </ul>
    </div>
    <div class="tuijian">
      <h2 class="hometitle">点击排行</h2>
      <ul class="tjpic">
        <i><img src="static/images/images/toppic01.jpg"></i>
        <p><a href="/">别让这些闹心的套路，毁了你的网页设计</a></p>
      </ul>
      <ul class="sidenews">
        <li> <i><img src="static/images/images/toppic01.jpg"></i>
          <p><a href="/">别让这些闹心的套路</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="static/images/images/toppic02.jpg"></i>
          <p><a href="/">给我模板PSD源文件，我给你设计HTML！</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="static/images/images/v1.jpg"></i>
          <p><a href="/">别让这些闹心的套路，毁了你的网页设计</a></p>
          <span>2018-05-13</span> </li>
        <li> <i><img src="static/images/images/v2.jpg"></i>
          <p><a href="/">给我模板PSD源文件，我给你设计HTML！</a></p>
          <span>2018-05-13</span> </li>
      </ul>
    </div>
    <div class="cloud">
      <h2 class="hometitle">标签云</h2>
      <ul>
        <a href="/">陌上花开</a> <a href="/">校园生活</a> <a href="/">html5</a> <a href="/">SumSung</a> <a href="/">青春</a> <a href="/">温暖</a> <a href="/">阳光</a> <a href="/">三星</a><a href="/">索尼</a> <a href="/">华维荣耀</a> <a href="/">三星</a> <a href="/">索尼</a>
      </ul>
    </div>
    <div class="links">
      <h2 class="hometitle">友情链接</h2>
      <ul>
        <li><a href="http://www.yangqq.com" target="_blank">杨青博客</a></li>
        <li><a href="http://www.yangqq.com" target="_blank">D设计师博客</a></li>
        <li><a href="http://www.yangqq.com" target="_blank">优秀个人博客</a></li>
      </ul>
    </div>
    <div class="guanzhu" id="float">
      <h2 class="hometitle">关注我们 么么哒！</h2>
      <ul>
        <li class="sina"><a href="/" target="_blank"><span>新浪微博</span>杨青博客</a></li>
        <li class="tencent"><a href="/" target="_blank"><span>腾讯微博</span>杨青博客</a></li>
        <li class="qq"><a href="/" target="_blank"><span>QQ号</span>476847113</a></li>
        <li class="email"><a href="/" target="_blank"><span>邮箱帐号</span>dancesmiling@qq.com</a></li>
        <li class="wxgzh"><a href="/" target="_blank"><span>微信号</span>yangqq_1987</a></li>
        <li class="wx"><img src="static/images/images/wx.jpg"></li>
      </ul>
    </div>
  </div>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>

templates/logon.html
<!DOCTYPE html>
<html>	
<head>
<title>Login</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="static/css/style1.css" rel='stylesheet' >
<!--webfonts-->

<!--//webfonts-->

</head>
<body>
{% block content %}
<form action="/logon" method="post"><br>
{% endblock %}
        {% csrf_token %}
        <div style="text-align:center; vertical-align:middel;"><h3>{{ msg }}</h3></div><br>
 <!--SIGN UP-->
	{% block content2 %}
 <h1>LOG ON</h1>
	{% endblock %}
<div class="login-form">
	<div class="close"> </div>
		<div class="head-info">
			<label class="lbl-1"> </label>
			<label class="lbl-2"> </label>
			<label class="lbl-3"> </label>
		</div>
			<div class="clear"> </div>
	<div class="avtar">
		<img src="static/img/avtar.png" />
	</div>
			<form>
					<input type="text" class="text" value="username" name="username" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Username';}" >
					<div class="key">
					<input type="password" value="password" name="password" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Password';}">

						</div>
			</form>
	<div class="signin">
		{% block content1 %}
		<input type="submit" value="Login" >
		{% endblock %}
	</div>
</div>
</body>
</html>

templates/post.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>JUST DO IT </title>
</head>
<body>
    <form action="/post" method="post">
        {% csrf_token %}
        <input type="text" name="q">
        <input type="text" name="p">
        <input type="submit" value="Submit">
    </form>

    <p>{{ rlt }}</p>
</body>
</html>

templates/search_form.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>JUST DO IT </title>
</head>
<body>
    <form action="/search" method="get">
        <input type="text" name="q">
        <input type="submit" value="搜索">
    </form>
</body>
</html>

templates/signup.html
{% extends 'logon.html' %}


{% block content %}
<form action="/signin" method="post"><br>
{% endblock %}
    {% block content2 %}
     <h1>SIGN UP</h1>
    {% endblock %}
    {% block content1 %}
    <input type="submit" value="sign up" >
		{% endblock %}